// NEXT REACT
import { GetStaticProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { SyntheticEvent, useState } from "react";

// DEPENDENCY (PACKAGES, LIBS, INTERFACES, TYPES)
import axios from "axios";
import Swal from "sweetalert2";
import { IDocumentData } from "@/interfaces/interfaces";
import prisma from "@/libs/prisma";

// COMPONENTS
import Layout from "@/components/Layout";

export const getStaticProps: GetStaticProps = async () => {
	const result = await prisma.document.findFirst({
		orderBy: {
			createdAt: "desc",
		},
	});

	const resultJSON = JSON.parse(JSON.stringify(result));

	const indexNomor = Number(resultJSON?.content?.nomor?.split(".")[0]) + 1;
	const indexYear = Number(resultJSON?.content?.nomor?.split("/")[2]);
	const yearNow = Number(new Date().getFullYear());
	const nomorDisposisi =
		resultJSON?.length === 0
			? `001.LD/PDKB/${yearNow}`
			: indexYear !== yearNow
			? `001.LD/PDKB/${yearNow}`
			: indexNomor < 10
			? `00${indexNomor}.LD/PDKB/${yearNow}`
			: indexNomor < 100
			? `0${indexNomor}.LD/PDKB/${yearNow}`
			: `${indexNomor}.LD/PDKB/${yearNow}`;

	return {
		props: {
			result: resultJSON,
			nomorDisposisi,
		},
	};
};

export default function Buat({ nomorDisposisi }: any) {
	const router = useRouter();

	const [disposisiContent, setDisposisiContent] = useState<
		IDocumentData | undefined
	>({
		content: {
			nomor: nomorDisposisi,
			diteruskanKepada: {
				direksi: false,
				manajemenRepresentative: false,
				auditorInternal: false,
				manajerSertifikasi: false,
				penanggungJawabTeknik: false,
				koordinatorPJT: false,
				tenagaTeknik: false,
				administratorUji: false,
				staffAdministrasi: false,
				staffKeuangan: false,
			},
			dikembalikanKepada: "",
			dikembalikanTanggal: "",
			resume: "",
			pemberi: "",
			penerima1: "",
			penerima2: "",
			jabatanPemberi: "",
			jabatanPenerima1: "",
			jabatanPenerima2: "",
		},
	});

	const handleSubmit = async (e: SyntheticEvent) => {
		e.preventDefault();
		try {
			await Swal.fire({
				title: "Buat Disposisi?",
				icon: "question",
				showCancelButton: true,
				color: "#111827",
				confirmButtonColor: "#60a5fa",
				cancelButtonColor: "#f87171",
				confirmButtonText: "Ya",
				cancelButtonText: "Batal",
			}).then((res) => {
				if (res.isConfirmed) {
					axios.post(
						"/api/documents",
						{
							content: disposisiContent,
							type: "DISPOSISI",
						},
						{
							headers: { "Content-Type": "application/json" },
						}
					);
					Swal.fire({
						title: "Disposisi berhasil dibuat!",
						icon: "success",
						color: "#111827",
						confirmButtonColor: "#60a5fa",
					}).then(() => {
						router.replace("/surat/disposisi");
					});
				}
			});
		} catch (error) {
			console.error(error);
		}
	};

	return (
		<>
			<Head>
				<title>GEMADISPOSISI - Buat Disposisi</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<h1 className="my-4 text-4xl font-semibold">Buat Disposisi</h1>
				<form
					onSubmit={handleSubmit}
					className="flex flex-col gap-4 w-full p-6 rounded-xl shadow-xl"
				>
					{/* NOMOR */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Nomor <span className="text-red-400">*</span>
						</label>
						<input
							required
							type="text"
							placeholder="..."
							defaultValue={nomorDisposisi}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										nomor: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* TANGGAL */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Tanggal <span className="text-red-400">*</span>
						</label>
						<input
							required
							type="date"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										tanggal: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* INDEKS */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Indeks <span className="text-red-400">*</span>
						</label>
						<select
							required
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										indeks: e.target.value,
									},
								})
							}
						>
							<option value="">--</option>
							<option value="RAHASIA">RAHASIA</option>
							<option value="PENTING">PENTING</option>
							<option value="BIASA_RUTIN">BIASA/RUTIN</option>
						</select>
					</div>
					{/* SURAT DARI */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Surat Dari <span className="text-red-400">*</span>
						</label>
						<input
							required
							type="text"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										suratDari: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* NOMOR SURAT */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Nomor Surat <span className="text-red-400">*</span>
						</label>
						<input
							required
							type="text"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										nomorSurat: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* TANGGAL SURAT */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Tanggal Surat <span className="text-red-400">*</span>
						</label>
						<input
							required
							type="date"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										tanggalSurat: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* PERIHAL */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Perihal <span className="text-red-400">*</span>
						</label>
						<input
							required
							type="text"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										perihal: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* TANGGAL DITERIMA */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Tanggal Diterima <span className="text-red-400">*</span>
						</label>
						<input
							required
							type="date"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										tanggalDiterima: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* DITERIMA MELAUI */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Diterima Melalui <span className="text-red-400">*</span>
						</label>
						<select
							required
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										diterimaMelalui: e.target.value,
									},
								})
							}
						>
							<option value="">--</option>
							<option value="EMAIL_WA">EMAIL/WA</option>
							<option value="POS_EKSPEDISI">POS/EKSPEDISI</option>
							<option value="LANGSUNG">LANGSUNG</option>
						</select>
					</div>
					{/* DITERUSKAN KEPADA */}
					<div className="flex gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 h-fit font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Diteruskan Kepada <span className="text-red-400">*</span>
						</label>
						<div className="flex flex-col md:flex-row gap-2 w-2/3 sm:w-3/4 bg-gray-200 px-4 py-2 rounded-md">
							<div className="flex flex-col gap-2 w-1/2">
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										className="w-5 h-5 accent-slate-800 rounded"
										onChange={(e) =>
											setDisposisiContent({
												...disposisiContent,
												content: {
													...disposisiContent?.content,
													diteruskanKepada: {
														...disposisiContent?.content?.diteruskanKepada,
														direksi:
															!disposisiContent?.content?.diteruskanKepada
																?.direksi,
													},
												},
											})
										}
									/>
									<p>Direksi</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										className="w-5 h-5 accent-slate-800 rounded"
										onChange={(e) =>
											setDisposisiContent({
												...disposisiContent,
												content: {
													...disposisiContent?.content,
													diteruskanKepada: {
														...disposisiContent?.content?.diteruskanKepada,
														manajemenRepresentative:
															!disposisiContent?.content?.diteruskanKepada
																?.manajemenRepresentative,
													},
												},
											})
										}
									/>
									<p>Manajemen Representative</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										className="w-5 h-5 accent-slate-800 rounded"
										onChange={(e) =>
											setDisposisiContent({
												...disposisiContent,
												content: {
													...disposisiContent?.content,
													diteruskanKepada: {
														...disposisiContent?.content?.diteruskanKepada,
														auditorInternal:
															!disposisiContent?.content?.diteruskanKepada
																?.auditorInternal,
													},
												},
											})
										}
									/>
									<p>Auditor Internal</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										className="w-5 h-5 accent-slate-800 rounded"
										onChange={(e) =>
											setDisposisiContent({
												...disposisiContent,
												content: {
													...disposisiContent?.content,
													diteruskanKepada: {
														...disposisiContent?.content?.diteruskanKepada,
														manajerSertifikasi:
															!disposisiContent?.content?.diteruskanKepada
																?.manajerSertifikasi,
													},
												},
											})
										}
									/>
									<p>Manajer Sertifikasi</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										className="w-5 h-5 accent-slate-800 rounded"
										onChange={(e) =>
											setDisposisiContent({
												...disposisiContent,
												content: {
													...disposisiContent?.content,
													diteruskanKepada: {
														...disposisiContent?.content?.diteruskanKepada,
														penanggungJawabTeknik:
															!disposisiContent?.content?.diteruskanKepada
																?.penanggungJawabTeknik,
													},
												},
											})
										}
									/>
									<p>Penanggung Jawab Teknik (PJT)</p>
								</div>
							</div>
							<div className="flex flex-col gap-2 w-1/2">
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										className="w-5 h-5 accent-slate-800 rounded"
										onChange={(e) =>
											setDisposisiContent({
												...disposisiContent,
												content: {
													...disposisiContent?.content,
													diteruskanKepada: {
														...disposisiContent?.content?.diteruskanKepada,
														koordinatorPJT:
															!disposisiContent?.content?.diteruskanKepada
																?.koordinatorPJT,
													},
												},
											})
										}
									/>
									<p>Koordinator PJT</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										className="w-5 h-5 accent-slate-800 rounded"
										onChange={(e) =>
											setDisposisiContent({
												...disposisiContent,
												content: {
													...disposisiContent?.content,
													diteruskanKepada: {
														...disposisiContent?.content?.diteruskanKepada,
														tenagaTeknik:
															!disposisiContent?.content?.diteruskanKepada
																?.tenagaTeknik,
													},
												},
											})
										}
									/>
									<p>Tenaga Teknik (TT/Asesor)</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										className="w-5 h-5 accent-slate-800 rounded"
										onChange={(e) =>
											setDisposisiContent({
												...disposisiContent,
												content: {
													...disposisiContent?.content,
													diteruskanKepada: {
														...disposisiContent?.content?.diteruskanKepada,
														administratorUji:
															!disposisiContent?.content?.diteruskanKepada
																?.administratorUji,
													},
												},
											})
										}
									/>
									<p>Administrator Uji</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										className="w-5 h-5 accent-slate-800 rounded"
										onChange={(e) =>
											setDisposisiContent({
												...disposisiContent,
												content: {
													...disposisiContent?.content,
													diteruskanKepada: {
														...disposisiContent?.content?.diteruskanKepada,
														staffAdministrasi:
															!disposisiContent?.content?.diteruskanKepada
																?.staffAdministrasi,
													},
												},
											})
										}
									/>
									<p>Staff Administrator</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										className="w-5 h-5 accent-slate-800 rounded"
										onChange={(e) =>
											setDisposisiContent({
												...disposisiContent,
												content: {
													...disposisiContent?.content,
													diteruskanKepada: {
														...disposisiContent?.content?.diteruskanKepada,
														staffKeuangan:
															!disposisiContent?.content?.diteruskanKepada
																?.auditorInternal,
													},
												},
											})
										}
									/>
									<p>Staff Keuangan</p>
								</div>
							</div>
						</div>
					</div>
					{/* ISI */}
					<div className="flex gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 h-fit font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Isi <span className="text-red-400">*</span>
						</label>
						<div className="flex flex-col gap-2 w-2/3 sm:w-3/4">
							<textarea
								rows={1}
								onChange={(e) =>
									setDisposisiContent({
										...disposisiContent,
										content: {
											...disposisiContent?.content,
											isi: e.target.value.split(",").map((v, k) => v.trim()),
										},
									})
								}
								required
								placeholder="..."
								className="outline-none bg-gray-200 px-4 py-2 rounded-md"
							></textarea>
							<p className="text-xs italic">
								Gunakan tanda koma (,) untuk memisahkan isi.
							</p>
						</div>
					</div>
					{/* DIKEMBALIKAN KEPADA */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Dikembalikan Kepada
						</label>
						<input
							type="text"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										dikembalikanKepada: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* DIKEMBALIKAN TANGGAL */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Dikembalikan Tanggal
						</label>
						<input
							type="date"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										dikembalikanTanggal: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* RESUME */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Resume
						</label>
						<select
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										resume: e.target.value,
									},
								})
							}
						>
							<option value="">--</option>
							<option value="SELESAI">SELESAI</option>
							<option value="BELUM_SELESAI">BELUM/TIDAK SELESAI</option>
							<option value="BUTUH_BARU">BUTUH BARU</option>
						</select>
					</div>
					{/* PEMBERI */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Pemberi <span className="text-red-400">*</span>
						</label>
						<input
							type="text"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										pemberi: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* JABATAN PEMBERI */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Jabatan Pemberi <span className="text-red-400">*</span>
						</label>
						<input
							type="text"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										jabatanPemberi: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* PENERIMA 1 */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Penerima 1 <span className="text-red-400">*</span>
						</label>
						<input
							type="text"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										penerima1: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* JABATAN PENERIMA 1 */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Jabatan Penerima 1 <span className="text-red-400">*</span>
						</label>
						<input
							type="text"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										jabatanPenerima1: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* PENERIMA 2 */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Penerima 2
						</label>
						<input
							type="text"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										penerima2: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* JABATAN PENERIMA 2 */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Jabatan Penerima 2
						</label>
						<input
							type="text"
							placeholder="..."
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							onChange={(e) =>
								setDisposisiContent({
									...disposisiContent,
									content: {
										...disposisiContent?.content,
										jabatanPenerima2: e.target.value,
									},
								})
							}
						/>
					</div>
					{/* BUTTON */}
					<div className="flex justify-end gap-2 text-white">
						<button
							type="button"
							className="px-4 py-2 bg-red-400 rounded-md transition-all duration-200 hover:bg-red-600"
						>
							Batal
						</button>
						<button
							type="submit"
							className="px-4 py-2 bg-blue-400 rounded-md transition-all duration-200 hover:bg-blue-600"
						>
							Buat Surat
						</button>
					</div>
				</form>
			</Layout>
		</>
	);
}
