// NEXT REACT
import { GetServerSideProps } from "next";
import Head from "next/head";
// DEPENDENCY (PACKAGES, LIBS, INTERFACES, TYPES)
import { getSession } from "next-auth/react";
import prisma from "@/libs/prisma";
import { IDocumentData, ISession } from "@/interfaces/interfaces";
// COMPONENTS
import Layout from "@/components/Layout";
import { useEffect } from "react";
import axios from "axios";

export const getServerSideProps: GetServerSideProps = async ({
	req,
	params,
}) => {
	const session = await getSession({ req });
	const disposisi = await prisma.document.findUnique({
		where: {
			id: params?.id as string,
		},
		select: {
			recipients: {
				select: {
					createdAt: true,
					recipientId: true,
					recipient: {
						select: {
							id: true,
							email: true,
							isActive: true,
							name: true,
							position: true,
							role: true,
						},
					},
				},
			},
			id: true,
			content: true,
			type: true,
			createdAt: true,
			author: true,
			authorId: true,
			isSent: true,
			isApproved: true,
		},
	});

	return {
		props: {
			session,
			disposisi: JSON.parse(JSON.stringify(disposisi)),
		},
	};
};

export default function View({
	disposisi,
	session,
}: {
	disposisi: IDocumentData;
	session: ISession;
}) {
	async function handleRead(): Promise<void> {
		if (session)
			try {
				await axios.put(
					"/api/userondocument",
					{ docId: disposisi?.id },
					{
						headers: { "Content-Type": "application/json" },
					}
				);
			} catch (error) {
				alert(error);
			}
	}
	useEffect(() => {
		handleRead();
	}, []);

	return (
		<>
			<Head>
				<title>GEMADISPOSISI - Disposisi</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<h1 className="my-4 text-4xl font-semibold">
					Disposisi - {disposisi?.content?.nomor}
				</h1>
				<form className="flex flex-col gap-4 w-full p-6 rounded-xl shadow-xl">
					{/* NOMOR */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Nomor
						</label>
						<input
							required
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.nomor}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* TANGGAL */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Tanggal
						</label>
						<input
							required
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.tanggal}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* INDEKS */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Indeks
						</label>
						<input
							required
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.indeks}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* SURAT DARI */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Surat Dari
						</label>
						<input
							required
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.suratDari}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* NOMOR SURAT */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Nomor Surat
						</label>
						<input
							required
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.nomorSurat}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* TANGGAL SURAT */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Tanggal Surat
						</label>
						<input
							required
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.tanggalSurat}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* PERIHAL */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Perihal
						</label>
						<input
							required
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.perihal}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* TANGGAL DITERIMA */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Tanggal Diterima
						</label>
						<input
							required
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.tanggalDiterima}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* DITERIMA MELAUI */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Diterima Melalui
						</label>
						<input
							required
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.diterimaMelalui}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* DITERUSKAN KEPADA */}
					<div className="flex gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 h-fit font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Diteruskan Kepada
						</label>
						<div className="flex flex-col md:flex-row gap-2 w-2/3 sm:w-3/4 bg-gray-200 px-4 py-2 rounded-md">
							<div className="flex flex-col gap-2 w-1/2">
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										defaultChecked={
											disposisi?.content?.diteruskanKepada?.direksi
										}
										className="w-5 h-5 accent-slate-800 rounded"
										disabled
									/>
									<p>Direksi</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										defaultChecked={
											disposisi?.content?.diteruskanKepada
												?.manajemenRepresentative
										}
										className="w-5 h-5 accent-slate-800 rounded"
										disabled
									/>
									<p>Manajemen Representative</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										defaultChecked={
											disposisi?.content?.diteruskanKepada?.auditorInternal
										}
										className="w-5 h-5 accent-slate-800 rounded"
										disabled
									/>
									<p>Auditor Internal</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										defaultChecked={
											disposisi?.content?.diteruskanKepada?.manajerSertifikasi
										}
										className="w-5 h-5 accent-slate-800 rounded"
										disabled
									/>
									<p>Manajer Sertifikasi</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										defaultChecked={
											disposisi?.content?.diteruskanKepada
												?.penanggungJawabTeknik
										}
										className="w-5 h-5 accent-slate-800 rounded"
										disabled
									/>
									<p>Penanggung Jawab Teknik (PJT)</p>
								</div>
							</div>
							<div className="flex flex-col gap-2 w-1/2">
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										defaultChecked={
											disposisi?.content?.diteruskanKepada?.koordinatorPJT
										}
										className="w-5 h-5 accent-slate-800 rounded"
										disabled
									/>
									<p>Koordinator PJT</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										defaultChecked={
											disposisi?.content?.diteruskanKepada?.tenagaTeknik
										}
										className="w-5 h-5 accent-slate-800 rounded"
										disabled
									/>
									<p>Tenaga Teknik (TT/Asesor)</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										defaultChecked={
											disposisi?.content?.diteruskanKepada?.administratorUji
										}
										className="w-5 h-5 accent-slate-800 rounded"
										disabled
									/>
									<p>Administrator Uji</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										defaultChecked={
											disposisi?.content?.diteruskanKepada?.staffAdministrasi
										}
										className="w-5 h-5 accent-slate-800 rounded"
										disabled
									/>
									<p>Staff Administrasi</p>
								</div>
								<div className="flex items-center gap-2">
									<input
										type="checkbox"
										defaultChecked={
											disposisi?.content?.diteruskanKepada?.staffKeuangan
										}
										className="w-5 h-5 accent-slate-800 rounded"
										disabled
									/>
									<p>Staff Keuangan</p>
								</div>
							</div>
						</div>
					</div>
					{/* ISI */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 h-fit font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Isi
						</label>
						<input
							required
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.isi}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* DIKEMBALIKAN KEPADA */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Dikembalikan Kepada
						</label>
						<input
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.dikembalikanKepada}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* DIKEMBALIKAN TANGGAL */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Dikembalikan Tanggal
						</label>
						<input
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.dikembalikanTanggal}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* RESUME */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Resume
						</label>
						<input
							required
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.resume}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* PEMBERI */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Pemberi
						</label>
						<input
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.pemberi}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* JABATAN PEMBERI */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Jabatan Pemberi
						</label>
						<input
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.jabatanPemberi}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* PENERIMA 1 */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Penerima 1
						</label>
						<input
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.penerima1}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* JABATAN PENERIMA 1 */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Jabatan Penerima 1
						</label>
						<input
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.jabatanPenerima1}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* PENERIMA 2 */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Penerima 2
						</label>
						<input
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.penerima2}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
					{/* JABATAN PENERIMA 2 */}
					<div className="flex items-center gap-6 w-full">
						<label className="w-1/3 sm:w-1/4 font-semibold bg-gray-800 px-4 py-2 rounded-md text-white">
							Jabatan Penerima 2
						</label>
						<input
							type="text"
							placeholder="..."
							defaultValue={disposisi?.content?.jabatanPenerima2}
							className="w-2/3 sm:w-3/4 outline-none bg-gray-200 px-4 py-2 rounded-md"
							disabled
						/>
					</div>
				</form>
			</Layout>
		</>
	);
}
